Repository palantir/tracing-java, pull requests merged in 2019-08, with the labels that each got.

#209 Remove jackson from api
  changelog/@unreleased/remove-jackson-api-dep.v2.yml
  tracing-api/build.gradle
  tracing-api/src/main/java/com/palantir/tracing/api/Span.java
Labels: autorelease, merge when ready

#206 Request log tracing
  changelog/@unreleased/pr-206.v2.yml
  readme.md
  tracing-api/src/main/java/com/palantir/tracing/api/OpenSpan.java
  tracing-api/src/main/java/com/palantir/tracing/api/TraceHttpHeaders.java
  tracing-okhttp3/src/main/java/com/palantir/tracing/okhttp3/OkhttpTraceInterceptor.java
  tracing-okhttp3/src/test/java/com/palantir/tracing/okhttp3/OkhttpTraceInterceptorTest.java
  tracing/src/main/java/com/palantir/tracing/Trace.java
  tracing/src/test/java/com/palantir/tracing/TraceTest.java
Labels: autorelease, merge when ready

#235 Test-utils to visualize spans
  build.gradle
  changelog/3.2.0-rc1/pr-235.v2.yml
  readme.md
  settings.gradle
  tracing-test-utils/build.gradle
  tracing-test-utils/src/main/java/com/palantir/tracing/ComparisonFailure_dataenum.java
  tracing-test-utils/src/main/java/com/palantir/tracing/HtmlFormatter.java
  tracing-test-utils/src/main/java/com/palantir/tracing/LayoutStrategy.java
  tracing-test-utils/src/main/java/com/palantir/tracing/RenderTracingRule.java
  tracing-test-utils/src/main/java/com/palantir/tracing/SpanAnalyzer.java
  tracing-test-utils/src/main/java/com/palantir/tracing/SpanComparator.java
  tracing-test-utils/src/main/java/com/palantir/tracing/TestTracing.java
  tracing-test-utils/src/main/java/com/palantir/tracing/TestTracingExtension.java
  tracing-test-utils/src/main/java/com/palantir/tracing/TestTracingSubscriber.java
  tracing-test-utils/src/main/java/com/palantir/tracing/TimeBounds.java
  tracing-test-utils/src/main/java/com/palantir/tracing/Utils.java
  tracing-test-utils/src/main/java/com/palantir/tracing/api/SerializableSpan.java
  tracing-test-utils/src/main/java/com/palantir/tracing/api/Serialization.java
  tracing-test-utils/src/main/resources/header.html
  tracing-test-utils/src/main/resources/span.html
  tracing-test-utils/src/test/java/com/palantir/tracing/HtmlFormatterTest.java
  tracing-test-utils/src/test/java/com/palantir/tracing/RenderTracingRuleDemo.java
  tracing-test-utils/src/test/java/com/palantir/tracing/TestTracingExtensionDemo.java
  tracing-test-utils/src/test/resources/log-receiver-CHRONOLOGICAL.html
  tracing-test-utils/src/test/resources/log-receiver-SPLIT_BY_TRACE.html
  tracing-test-utils/src/test/resources/log-receiver.txt
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_multiple_root_spans.log
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_single_root_span/foo 1 bar 1.log
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_single_root_span/foo 2 bar 2.log
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_single_root_span/foo 3 bar 3.log
  tracing/src/test/java/com/palantir/tracing/CloseableTracerTest.java
  versions.lock
  versions.props
Labels: no changelog

#242 Correctly exclude spans emitted during beforeEach
  tracing-test-utils/src/main/java/com/palantir/tracing/TestTracingExtension.java
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_multiple_root_spans.log
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_single_root_span/foo 1 bar 1.log
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_single_root_span/foo 2 bar 2.log
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_trace_with_single_root_span/foo 3 bar 3.log
Labels: no changelog

#243 don't publish test utils just yet
  tracing-test-utils/build.gradle
Labels: merge when ready, no changelog

#244 Add tracing demos
  settings.gradle
  tracing-demos/build.gradle
  tracing-demos/src/test/java/com/palantir/tracing/TracingDemos.java
  tracing-demos/src/test/resources/tracing/TracingDemos/async_future.log
  tracing-demos/src/test/resources/tracing/TracingDemos/backoffs_on_a_scheduled_executor.log
  tracing-demos/src/test/resources/tracing/TracingDemos/handles_async_spans.log
  tracing-demos/src/test/resources/tracing/TracingDemos/multi_producer_single_consumer.log
  tracing-demos/src/test/resources/tracing/TracingDemos/transformed_future.log
  tracing-test-utils/src/main/java/com/palantir/tracing/SpanAnalyzer.java
Labels: merge when ready, no changelog
