Repository palantir/tracing-java, pull requests merged in 2019-09, with the labels that each got.

#247 tweaks to ckozak's DetachedSpan & demo usage
  tracing-demos/src/test/java/com/palantir/tracing/TracingDemos.java
  tracing-demos/src/test/resources/tracing/TracingDemos/async_future.log
  tracing-demos/src/test/resources/tracing/TracingDemos/backoffs_on_a_scheduled_executor.log
  tracing-demos/src/test/resources/tracing/TracingDemos/handles_async_spans.log
  tracing-demos/src/test/resources/tracing/TracingDemos/multi_producer_single_consumer.log
  tracing-demos/src/test/resources/tracing/TracingDemos/transformed_future.log
  tracing-test-utils/src/main/java/com/palantir/tracing/HtmlFormatter.java
  tracing-test-utils/src/main/java/com/palantir/tracing/TimeBounds.java
  tracing-test-utils/src/test/java/com/palantir/tracing/TestTracingExtensionDemo.java
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_async_spans.log
  tracing/src/main/java/com/palantir/tracing/CloseableSpan.java
  tracing/src/main/java/com/palantir/tracing/CloseableTracer.java
  tracing/src/main/java/com/palantir/tracing/DetachedSpan.java
  tracing/src/main/java/com/palantir/tracing/Tracer.java
  tracing/src/test/java/com/palantir/tracing/TracerTest.java
Labels: merge when ready

#249 Tracer#getTraceMetadata [into ckozak/detached_tracing_api]
  tracing/src/main/java/com/palantir/tracing/CloseableSpan.java
  tracing/src/main/java/com/palantir/tracing/TraceMetadata.java
  tracing/src/main/java/com/palantir/tracing/Tracer.java
Labels: no changelog

#250 Improve tracing-test-utils
  changelog/@unreleased/pr-250.v2.yml
  tracing-test-utils/src/main/java/com/palantir/tracing/HtmlFormatter.java
  tracing-test-utils/src/main/java/com/palantir/tracing/TimeBounds.java
  tracing-test-utils/src/main/java/com/palantir/tracing/api/SerializableSpan.java
  tracing-test-utils/src/main/java/com/palantir/tracing/api/Serialization.java
  tracing-test-utils/src/test/java/com/palantir/tracing/SpanAnalyzerTest.java
  tracing-test-utils/src/test/resources/cjr-test-1/spans-1.log
  tracing-test-utils/src/test/resources/cjr-test-1/spans-2.log
Labels: merge when ready

#124 Support for tracing asynchronous operations
  changelog/@unreleased/pr-124.v2.yml
  tracing-demos/src/test/java/com/palantir/tracing/TracingDemos.java
  tracing-demos/src/test/resources/tracing/TracingDemos/async_future.log
  tracing-demos/src/test/resources/tracing/TracingDemos/backoffs_on_a_scheduled_executor.log
  tracing-demos/src/test/resources/tracing/TracingDemos/handles_async_spans.log
  tracing-demos/src/test/resources/tracing/TracingDemos/multi_producer_single_consumer.log
  tracing-demos/src/test/resources/tracing/TracingDemos/transformed_future.log
  tracing-okhttp3/src/main/java/com/palantir/tracing/OkhttpTraceInterceptor2.java
  tracing-okhttp3/src/main/java/com/palantir/tracing/okhttp3/OkhttpTraceInterceptor.java
  tracing-okhttp3/src/test/java/com/palantir/tracing/okhttp3/OkhttpTraceInterceptorTest.java
  tracing-test-utils/src/main/java/com/palantir/tracing/RenderTracingRule.java
  tracing-test-utils/src/main/java/com/palantir/tracing/Utils.java
  tracing-test-utils/src/test/java/com/palantir/tracing/TestTracingExtensionDemo.java
  tracing-test-utils/src/test/resources/tracing/TestTracingExtensionDemo/handles_async_spans.log
  tracing/src/main/java/com/palantir/tracing/AsyncTracer.java
  tracing/src/main/java/com/palantir/tracing/CloseableSpan.java
  tracing/src/main/java/com/palantir/tracing/CloseableTracer.java
  tracing/src/main/java/com/palantir/tracing/DetachedSpan.java
  tracing/src/main/java/com/palantir/tracing/TraceMetadata.java
  tracing/src/main/java/com/palantir/tracing/Tracer.java
  tracing/src/test/java/com/palantir/tracing/AsyncTracerTest.java
  tracing/src/test/java/com/palantir/tracing/TracerTest.java
Labels: autorelease, merge when ready

#260 Pass nullaway
  build.gradle
  tracing-jaxrs/src/main/java/com/palantir/tracing/jaxrs/JaxRsTracers.java
  tracing-jersey/src/main/java/com/palantir/tracing/jersey/TraceEnrichingFilter.java
  tracing/src/main/java/com/palantir/tracing/DeferredTracer.java
  tracing/src/main/java/com/palantir/tracing/Tracers.java
  versions.props
Labels: merge when ready, no changelog
